version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ANSKk08aPEDbFjDO
      MYSQL_DATABASE: testing
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # porta do Nuxt
      - "3333:3333" # porta do backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ANSKk08aPEDbFjDO
      DB_NAME: testing
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
